trigger:
  - '*'

pr:
  - '*'

resources:
  repositories:
    - repository: self
    - repository: templates
      type: github
      endpoint: project-origin
      name: project-origin/pipeline-templates

variables:
  - name: releaseName
    value: 'example-backend'
  - name: imageName
    value: 'projectorigin/$(releaseName)'
  - template: vars.yml@templates

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - template: job-run-pytest.yml@templates

  # image build and deploy requires the kubeCon and other variable sto be defined in a variable group in Azure DevOps
  - ${{ if ne(variables['kubeCon'], '') }}:

    - template: job-docker-build.yml@templates
      parameters:
        dependsOn: run_pytest
        imageName: $(imageName)
        tag: $(tag)
        
    - template: job-deploy.yml@templates
      parameters:
        dependsOn: docker_build
        kubeCon: $(kubeCon)
        namespace: $(namespace)
        releaseName: $(releaseName)
        deploymentEnvironment: $(deploymentEnvironment)
        overrideValues: tag=$(tag)
        pool:
          ${{ if ne(variables['poolName'], '') }}:
            name: $(poolName)
          ${{ if eq(variables['poolName'], '') }}:
            vmImage: 'ubuntu-latest'