apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-backend-deployment
  template:
    metadata:
      labels:
        app: example-backend-deployment
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: example-backend-container
          image: projectorigin/example-backend:{{ .Values.tag }}
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: namespace-config
            - configMapRef:
                name: example-backend-config
            - secretRef:
                name: example-backend-system-secret
            - secretRef:
                name: example-backend-hydra-secret
            - secretRef:
                name: example-backend-db-secret
            - secretRef:
                name: example-backend-webhook-secret
          env:
            - name: SERVICE_NAME
              value: ExampleBackend
            - name: WORKERS
              value: "{{ .Values.workers }}"
            - name: WORKER_CONNECTIONS
              value: "{{ .Values.workerconnections }}"
#          resources:
#            requests:
#              memory: "1000Mi"
#              cpu: "250m"
#            limits:
#              memory: "2500Mi"
#              cpu: "1000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-backend-beat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-backend-beat-deployment
  template:
    metadata:
      labels:
        app: example-backend-beat-deployment
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: example-backend-beat-container
          image: projectorigin/example-backend:{{ .Values.tag }}
          args: ["./entrypoint.beat.sh"]
          envFrom:
            - configMapRef:
                name: namespace-config
            - configMapRef:
                name: example-backend-config
            - secretRef:
                name: example-backend-system-secret
            - secretRef:
                name: example-backend-hydra-secret
            - secretRef:
                name: example-backend-db-secret
            - secretRef:
                name: example-backend-webhook-secret
          env:
            - name: SERVICE_NAME
              value: ExampleBackendBeat
#          resources:
#            requests:
#              memory: "100Mi"
#              cpu: "100m"
#            limits:
#              memory: "250Mi"
#              cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-backend-worker-deployment
spec:
  replicas: {{ .Values.workerreplicas }}
  selector:
    matchLabels:
      app: example-backend-worker-deployment
  template:
    metadata:
      labels:
        app: example-backend-worker-deployment
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: example-backend-worker-container
          image: projectorigin/example-backend:{{ .Values.tag }}
          args: ["./entrypoint.worker.sh"]

          envFrom:
            - configMapRef:
                name: namespace-config
            - configMapRef:
                name: example-backend-config
            - secretRef:
                name: example-backend-system-secret
            - secretRef:
                name: example-backend-hydra-secret
            - secretRef:
                name: example-backend-db-secret
            - secretRef:
                name: example-backend-webhook-secret
          env:
            - name: SERVICE_NAME
              value: ExampleBackendWorker
            - name: CONCURRENCY
              value: "{{ .Values.concurrency }}"
#          resources:
#            requests:
#              memory: "250Mi"
#              cpu: "1000m"
#            limits:
#              memory: "2000Mi"
#              cpu: "2000m"
