"""empty message

Revision ID: 61b29135dba7
Revises: 97120165f3c1
Create Date: 2020-07-27 20:23:21.738503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61b29135dba7'
down_revision = '97120165f3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements_agreement', sa.Column('facility_ids', postgresql.ARRAY(sa.Integer()), nullable=True))

    op.execute("""
        UPDATE agreements_agreement AS a
        SET facility_ids = ARRAY(
            SELECT facility_id
            FROM agreements_facility_association
            WHERE agreement_id = a.id
        )
    """)

    op.drop_index('ix_agreements_facility_association_agreement_id', table_name='agreements_facility_association')
    op.drop_index('ix_agreements_facility_association_facility_id', table_name='agreements_facility_association')
    op.drop_table('agreements_facility_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements_agreement', 'facility_ids')
    op.create_table('agreements_facility_association',
    sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('facility_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements_agreement.id'], name='agreements_facility_association_agreement_id_fkey'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities_facility.id'], name='agreements_facility_association_facility_id_fkey'),
    sa.UniqueConstraint('agreement_id', 'facility_id', name='agreements_facility_association_agreement_id_facility_id_key')
    )
    op.create_index('ix_agreements_facility_association_facility_id', 'agreements_facility_association', ['facility_id'], unique=False)
    op.create_index('ix_agreements_facility_association_agreement_id', 'agreements_facility_association', ['agreement_id'], unique=False)
    # ### end Alembic commands ###
