"""empty message

Revision ID: 6567fcfb3093
Revises: 
Create Date: 2020-04-26 14:59:50.114376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6567fcfb3093'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_expire', sa.DateTime(), nullable=False),
    sa.Column('has_performed_onboarding', sa.Boolean(), nullable=False),
    sa.Column('is_importing_facilities', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_sub'), 'auth_user', ['sub'], unique=True)
    op.create_table('agreements_agreement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_proposed_id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', 'WITHDRAWN', name='agreementstate'), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('Wh', 'KWh', 'MWh', 'GWh', name='unit'), nullable=False),
    sa.Column('technology', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_from_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['user_proposed_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_agreements_agreement_id'), 'agreements_agreement', ['id'], unique=False)
    op.create_index(op.f('ix_agreements_agreement_public_id'), 'agreements_agreement', ['public_id'], unique=False)
    op.create_index(op.f('ix_agreements_agreement_state'), 'agreements_agreement', ['state'], unique=False)
    op.create_index(op.f('ix_agreements_agreement_user_from_id'), 'agreements_agreement', ['user_from_id'], unique=False)
    op.create_index(op.f('ix_agreements_agreement_user_proposed_id'), 'agreements_agreement', ['user_proposed_id'], unique=False)
    op.create_index(op.f('ix_agreements_agreement_user_to_id'), 'agreements_agreement', ['user_to_id'], unique=False)
    op.create_table('disclosures_disclosure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_disclosures_disclosure_id'), 'disclosures_disclosure', ['id'], unique=False)
    op.create_index(op.f('ix_disclosures_disclosure_public_id'), 'disclosures_disclosure', ['public_id'], unique=False)
    op.create_index(op.f('ix_disclosures_disclosure_slug'), 'disclosures_disclosure', ['slug'], unique=True)
    op.create_index(op.f('ix_disclosures_disclosure_user_id'), 'disclosures_disclosure', ['user_id'], unique=False)
    op.create_table('facilities_facility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gsrn', sa.String(), nullable=True),
    sa.Column('facility_type', sa.String(), nullable=False),
    sa.Column('technology', sa.String(), nullable=True),
    sa.Column('technology_code', sa.String(), nullable=True),
    sa.Column('fuel_code', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('street_code', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('building_number', sa.String(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('municipality_code', sa.String(), nullable=True),
    sa.Column('retiring_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gsrn'),
    sa.UniqueConstraint('user_id', 'retiring_priority')
    )
    op.create_index(op.f('ix_facilities_facility_gsrn'), 'facilities_facility', ['gsrn'], unique=False)
    op.create_index(op.f('ix_facilities_facility_id'), 'facilities_facility', ['id'], unique=False)
    op.create_index(op.f('ix_facilities_facility_public_id'), 'facilities_facility', ['public_id'], unique=False)
    op.create_index(op.f('ix_facilities_facility_user_id'), 'facilities_facility', ['user_id'], unique=False)
    op.create_table('agreements_facility_association',
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements_agreement.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities_facility.id'], ),
    sa.UniqueConstraint('agreement_id', 'facility_id')
    )
    op.create_index(op.f('ix_agreements_facility_association_agreement_id'), 'agreements_facility_association', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_agreements_facility_association_facility_id'), 'agreements_facility_association', ['facility_id'], unique=False)
    op.create_table('disclosures_facility_association',
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures_disclosure.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities_facility.id'], ),
    sa.UniqueConstraint('disclosure_id', 'facility_id')
    )
    op.create_index(op.f('ix_disclosures_facility_association_disclosure_id'), 'disclosures_facility_association', ['disclosure_id'], unique=False)
    op.create_index(op.f('ix_disclosures_facility_association_facility_id'), 'disclosures_facility_association', ['facility_id'], unique=False)
    op.create_table('facilities_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities_facility.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'tag')
    )
    op.create_index(op.f('ix_facilities_tag_facility_id'), 'facilities_tag', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facilities_tag_id'), 'facilities_tag', ['id'], unique=False)
    op.create_index(op.f('ix_facilities_tag_tag'), 'facilities_tag', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facilities_tag_tag'), table_name='facilities_tag')
    op.drop_index(op.f('ix_facilities_tag_id'), table_name='facilities_tag')
    op.drop_index(op.f('ix_facilities_tag_facility_id'), table_name='facilities_tag')
    op.drop_table('facilities_tag')
    op.drop_index(op.f('ix_disclosures_facility_association_facility_id'), table_name='disclosures_facility_association')
    op.drop_index(op.f('ix_disclosures_facility_association_disclosure_id'), table_name='disclosures_facility_association')
    op.drop_table('disclosures_facility_association')
    op.drop_index(op.f('ix_agreements_facility_association_facility_id'), table_name='agreements_facility_association')
    op.drop_index(op.f('ix_agreements_facility_association_agreement_id'), table_name='agreements_facility_association')
    op.drop_table('agreements_facility_association')
    op.drop_index(op.f('ix_facilities_facility_user_id'), table_name='facilities_facility')
    op.drop_index(op.f('ix_facilities_facility_public_id'), table_name='facilities_facility')
    op.drop_index(op.f('ix_facilities_facility_id'), table_name='facilities_facility')
    op.drop_index(op.f('ix_facilities_facility_gsrn'), table_name='facilities_facility')
    op.drop_table('facilities_facility')
    op.drop_index(op.f('ix_disclosures_disclosure_user_id'), table_name='disclosures_disclosure')
    op.drop_index(op.f('ix_disclosures_disclosure_slug'), table_name='disclosures_disclosure')
    op.drop_index(op.f('ix_disclosures_disclosure_public_id'), table_name='disclosures_disclosure')
    op.drop_index(op.f('ix_disclosures_disclosure_id'), table_name='disclosures_disclosure')
    op.drop_table('disclosures_disclosure')
    op.drop_index(op.f('ix_agreements_agreement_user_to_id'), table_name='agreements_agreement')
    op.drop_index(op.f('ix_agreements_agreement_user_proposed_id'), table_name='agreements_agreement')
    op.drop_index(op.f('ix_agreements_agreement_user_from_id'), table_name='agreements_agreement')
    op.drop_index(op.f('ix_agreements_agreement_state'), table_name='agreements_agreement')
    op.drop_index(op.f('ix_agreements_agreement_public_id'), table_name='agreements_agreement')
    op.drop_index(op.f('ix_agreements_agreement_id'), table_name='agreements_agreement')
    op.drop_table('agreements_agreement')
    op.drop_index(op.f('ix_auth_user_sub'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
