"""empty message

Revision ID: 8a09a3767300
Revises: 262b0f529fb1
Create Date: 2020-09-08 10:31:26.165094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a09a3767300'
down_revision = '262b0f529fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements_agreement', sa.Column('facility_gsrn', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('agreements_agreement', 'facility_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements_agreement', sa.Column('facility_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('agreements_agreement', 'facility_gsrn')
    # ### end Alembic commands ###
