"""empty message

Revision ID: 8cd48209b24c
Revises: 1ec978d38bb7
Create Date: 2020-06-04 06:37:35.979008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd48209b24c'
down_revision = '1ec978d38bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'last_login')
    # ### end Alembic commands ###
