"""empty message

Revision ID: 97120165f3c1
Revises: c9e99dd24160
Create Date: 2020-07-27 11:32:40.446236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97120165f3c1'
down_revision = 'c9e99dd24160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements_agreement', sa.Column('amount_percent', sa.Integer(), nullable=True))
    op.create_check_constraint(
        "amount_percent_is_NULL_or_between_1_and_100",
        "agreements_agreement",
        "(amount_percent IS NULL) OR (amount_percent >= 1 AND amount_percent <= 100)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "amount_percent_is_NULL_or_between_0_and_100",
        "agreements_agreement")
    op.drop_column('agreements_agreement', 'amount_percent')
    # ### end Alembic commands ###
