"""empty message

Revision ID: 9924ecf8a3e1
Revises: b1eb061d4c73
Create Date: 2020-05-13 12:03:17.519710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9924ecf8a3e1'
down_revision = 'b1eb061d4c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('company', sa.String(), nullable=True))
    op.add_column('auth_user', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'phone')
    op.drop_column('auth_user', 'company')
    # ### end Alembic commands ###
