"""empty message

Revision ID: bcf165b20f3b
Revises: 8cd48209b24c
Create Date: 2020-06-16 13:56:39.333736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcf165b20f3b'
down_revision = '8cd48209b24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements_agreement', sa.Column('limit_to_consumption', sa.Boolean(), nullable=True))
    op.alter_column('agreements_agreement', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agreements_agreement', 'unit',
               existing_type=postgresql.ENUM('Wh', 'kWh', 'MWh', 'GWh', name='unit'),
               nullable=True)
    op.create_check_constraint(
        "limit_to_consumption_OR_amount_and_unit",
        "agreements_agreement",
        "(limit_to_consumption = 'f' and amount is not null and unit is not null) or (limit_to_consumption = 't')")
    op.execute("UPDATE agreements_agreement SET limit_to_consumption = 'f'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "limit_to_consumption_OR_amount_and_unit",
        "agreements_agreement")
    op.alter_column('agreements_agreement', 'unit',
               existing_type=postgresql.ENUM('Wh', 'kWh', 'MWh', 'GWh', name='unit'),
               nullable=False)
    op.alter_column('agreements_agreement', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('agreements_agreement', 'limit_to_consumption')
    # ### end Alembic commands ###
