"""empty message

Revision ID: c36213b104ad
Revises: 8cd48209b24c
Create Date: 2020-06-08 09:33:30.994867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36213b104ad'
down_revision = '8cd48209b24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update pg_enum set enumlabel = 'kWh' where enumlabel ='KWh';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update pg_enum set enumlabel = 'KWh' where enumlabel ='kWh';")
    # ### end Alembic commands ###
