"""empty message

Revision ID: c9e99dd24160
Revises: bcf165b20f3b
Create Date: 2020-07-24 10:30:03.608205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e99dd24160'
down_revision = 'bcf165b20f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements_agreement', sa.Column('transfer_priority', sa.Integer(), nullable=True))
    #op.create_unique_constraint(None, 'agreements_agreement', ['user_from_id', 'transfer_priority'])

    op.execute("""
    update agreements_agreement
    set transfer_priority = s.row_number - 1
    from (
        select a.id, row_number() over (
            partition by a.user_from_id order by a.created asc
        )
        from agreements_agreement as a
        where a.state = 'ACCEPTED'
    ) as s
    where agreements_agreement.id = s.id""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements_agreement', 'transfer_priority')
    # ### end Alembic commands ###
