# """empty message
#
# Revision ID: b29d2de6b334
# Revises: 8a09a3767300
# Create Date: 2020-09-22 14:04:57.559145
#
# """
# from alembic import op
# import sqlalchemy as sa
#
#
# # revision identifiers, used by Alembic.
# revision = 'b29d2de6b334'
# down_revision = '8a09a3767300'
# branch_labels = None
# depends_on = None
#
#
# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('auth_user', sa.Column('disabled', sa.Boolean(), nullable=True))
#     op.execute("UPDATE auth_user SET disabled='f';")
#     op.alter_column('auth_user', 'disabled',
#                existing_type=sa.BOOLEAN(),
#                nullable=False)
#     # ### end Alembic commands ###
#
#
# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('auth_user', 'disabled')
#     # ### end Alembic commands ###
